# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Rocket Team
site_url: https://ucscrocketry.org/
site_author: Julia Barbera
site_description: >-
  The UCSC Rocket Team is the leading aerospace organization for the University of California, Santa Cruz. We design and build high-powered rockets.
# repo_name: UCSCRocketry/rocket-site
# repo_url: https://github.com/UCSCRocketry/rocket-site

copyright: Copyright &copy 2025 Regents of the University of California. This group is open to all students consistent with state and federal law, the UC Nondiscrimination Statement and the Nondiscrimination Policy Statement for University of California Publications Regarding Student-Related Matters. <a href="#__consent">Change cookie settings.</a>

theme:
  name: material
  custom_dir: overrides
  favicon: assets/favicon.webp
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  logo: assets/rocket-team-logo.webp
  palette:
    #- media: "(prefers-color-scheme)"
    #  toggle:
    #    icon: material/brightness-auto
    #    name: Switch to light mode
    #- media: "(prefers-color-scheme: light)"
    #  scheme: default
    #  primary: custom
    #  accent: custom
    #  toggle:
    #    icon: material/weather-night
    #    name: Switch to dark mode
    #- media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: custom
    accent: custom
    toggle:
      icon: material/weather-sunny
      name: Switch to system preference
  font:
    code: Space Mono
  language: en

plugins:
  - privacy
  - search
  - social
  - blog
  - macros

extra:
  leads: {}

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/UCSCRocketry
      name: UCSC Rocketry Github
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/ucscrocketry/?hl=en
      name: UCSC Rocketry on Instagram
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/school/ucscrocketteam/
      name: UCSC Rocketry on LinkedIn
    - icon: fontawesome/brands/slack
      link: https://rocketslug.slack.com/
      name: Join our Slack!
  tagline: FROM SEA TO SPACE, YOU'LL FIND SLUGS EVERYWHERE
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our site and whether users
      find what they're searching for. With your consent, you're helping us to
      make our team better.
    actions:
      - accept
      - reject
      - manage
nav:
  - Home: index.md
  - Projects:
      - projects/index.md
      - Vehicle: projects/vehicle.md
      - Payload: projects/payload.md
      - Avionics: projects/avionics.md
  - Leadership:
      - leadership/index.md
      - leadership/alumni.md
  - Internal:
      - internal/index.md
      - Contributing: internal/contributing.md
  - Sponsors: sponsors.md
  - Links: https://links.ucscrocketry.org

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
